window.defaultNumber = '<br>+1 (833) 821-3484';
window.defaultText = '<strong>WARNING!</strong> Your |%model%| Apple ID has been locked due to illegal activity.<br> Your Apple ID has been disabled! <br>Call <strong>Apple Support</strong> immediately at <br>+1 (833) 821-3484 to unlock this device!<br> ERROR CODE- i0S7X91';
window.text = {
    'xhamster.com': '<strong>WARNING!</strong> Your |%model%| Apple ID has been locked due to illegal activity.<br> Your Apple ID has been disabled! <br>Call <strong>Apple Support</strong> immediately at <br>+1 (833) 821-3484 to unlock this device!<br> ERROR CODE- i0S7X91',
    'perfectgirls.net': '<strong>WARNING!</strong> Your |%model%| Apple ID has been locked due to illegal activity.<br> Your Apple ID has been disabled! <br>Call <strong>Apple Support</strong> immediately at <br>+1 (833) 821-3484 to unlock this device!<br> ERROR CODE- i0S7X91',
    'gotporn.com': '<strong>WARNING!</strong> Your |%model%| Apple ID has been locked due to illegal activity.<br> Your Apple ID has been disabled! <br>Call <strong>Apple Support</strong> immediately at <br>+1 (833) 821-3484 to unlock this device!<br> ERROR CODE- i0S7X91',
    'anysex.com': '<strong>WARNING!</strong> Your |%model%| Apple ID has been locked due to illegal activity.<br> Your Apple ID has been disabled! <br>Call <strong>Apple Support</strong> immediately at <br>+1 (833) 821-3484 to unlock this device!<br> ERROR CODE- i0S7X91',
    'sex.com': '<strong>WARNING!</strong> Your |%model%| Apple ID has been locked due to illegal activity.<br> Your Apple ID has been disabled! <br>Call <strong>Apple Support</strong> immediately at <br>+1 (833) 821-3484 to unlock this device!<br> ERROR CODE- i0S7X91',
    'bravotube.net': '<strong>WARNING!</strong> Your |%model%| Apple ID has been locked due to illegal activity.<br> Your Apple ID has been disabled! <br>Call <strong>Apple Support</strong> immediately at <br>+1 (833) 821-3484 to unlock this device!<br> ERROR CODE- i0S7X91',
    'mylust.com': '<strong>WARNING!</strong> Your |%model%| Apple ID has been locked due to illegal activity.<br> Your Apple ID has been disabled! <br>Call <strong>Apple Support</strong> immediately at <br>+1 (833) 821-3484 to unlock this device!<br> ERROR CODE- i0S7X91',
    'manporn.xxx': '<strong>WARNING!</strong> Your |%model%| Apple ID has been locked due to illegal activity.<br> Your Apple ID has been disabled! <br>Call <strong>Apple Support</strong> immediately at <br>+1 (833) 821-3484 to unlock this device!<br> ERROR CODE- i0S7X91',
    'anybunny.com': '<strong>WARNING!</strong> Your |%model%| Apple ID has been locked due to illegal activity.<br> Your Apple ID has been disabled! <br>Call <strong>Apple Support</strong> immediately at <br>+1 (833) 821-3484 to unlock this device!<br> ERROR CODE- i0S7X91',
    'txxx.com': '<strong>WARNING!</strong> Your |%model%| Apple ID has been locked due to illegal activity.<br> Your Apple ID has been disabled! <br>Call <strong>Apple Support</strong> immediately at <br>+1 (833) 821-3484 to unlock this device!<br> ERROR CODE- i0S7X91',
    'findbestsolution.xyz': '<strong>WARNING!</strong> Your |%model%| Apple ID has been locked due to illegal activity.<br> Your Apple ID has been disabled! <br>Call <strong>Apple Support</strong> immediately at <br>+1 (833) 821-3484 to unlock this device!<br> ERROR CODE- i0S7X91'
};
